export const constants = {
    fullnameLabel: 'Nome Completo',
    emailLabel: 'Email',
    passwordLabel: 'Senha',
    repeatPasswordLabel: 'Confirme a senha',
    btnLogin: 'Logar',
    btnSignup: 'Cadastrar',
    btnGoToSignUp: 'Quero me registrar',
    btnGoToSignIn: 'Já sou cadastrado',
    signupTitle: 'Registrar',
    loginTitle: 'Entrar',
    
    pgcompTitle: 'PGCOMP',
    progLabel: 'Programa de Pós-graduação',
    ccLabel: 'em Ciência da Computação',
    formDesc: 'O presente formulário se destina a comprovação dos dados referentes ao Edital 06/2019 do Programa de Pós-Graduação em Computação - PGCOMP da Universidade Federal da Bahia - UFBA.',
    fullnameReq: 'Nome Completo *',
    emailReq: 'Email *',
    phoneReq: 'Celular *',
    orienReq: 'Nome do Orientador *',
    semesterEntryReq: 'Semestre de Entrada *',
    underUnivReq: 'Universidade em que cursou a graduação *',
    lattesLinkReq: 'Link para CV Lattes *',
    linkEnade: 'Link para ENADE',
    courseReq: 'Curso do Candidato(a) *',
    mestradoLabel: 'Mestrado',
    doctorLabel: 'Doutorado',
    mastersFreshman: 'Sou ingressante de mestrado.',
    scoreUndergrad: 'Coeficiente de Rendimento da Graduação',
    iraLabel: 'IRA (Índice de Rendimento Acadêmico)',
    crLabel: 'CR (Coeficiente de Rendimento)',
    gradeLabel: 'Notas por Conceito',
    conceitoReq: 'Conceito *',
    noteReq: 'Nota *',
    enadeReq: 'ENADE do seu Curso de Graduação *',
    areaReq: 'Área do seu Curso de Graduação *',
    compLabel: 'Ciência da Computação, Sistemas de Informação, Licenciatura em Computação, Engenharia da Computação e Engenharia de Software',
    matLabel: 'Matemática Computacional, Matemática, Estatística, Física e Engenharia Elétrica (e correlatas)',
    otherExactLabel: 'Outras Ciências Exatas',
    otherLabel: 'Outras Áreas',
    crPos: 'Coeficiente de Rendimento em Programas de Pós Graduação Stricto Sensu',
    noteCRPG: 'Nota *',
    capesReq: 'Conceito CAPES *',
    intelectProd: 'Produções Intelectuais',
    publiLabel: 'Publicação',
    categLabel: 'Categoria *',
    fullArt: 'Artigos Completos',
    sbc: 'Sem QUALIS mas com selo SBC',
    otherTypes: 'Outros Tipos',
    patent: 'Patente Depositada',
    book: 'Livro',
    chapter: 'Capítulo de Livro ou Organização de Livro',
    summary: 'Resumo Estendido',
    minicurso: 'Minicurso ou Tutorial Ministrado em Conferência',
    relatorio: 'Relatório Técnico do PGCOMP',
    linkLabel: 'Link',
    fileLabel: 'Arquivo',
    publiLinkReq: 'Link para a Publicação *',
    publiFile: 'Arquivo Publicação *',
    addFile: 'Adicionar Arquivo',
    remove: 'Remover',
    update: 'Atualizar',
    subscribe: "Inscrever-se",
    proceedingsLink: 'Link para os Anais',
    eventLink: 'Link do Evento',
    graduateTranscript: 'Histórico acadêmico de curso(s) de Pós-Graduação Strictu Sensu',
    undergradTranscript: 'Histórico acadêmico de curso(s) de graduação (em PDF, apenas para mestrandos)',

    valueA: 'A',
    valueB: 'B',
    valueC: 'C',
    valueD: 'D',
    valueE: 'E',

    value1: '1',
    value2: '2',
    value3: '3',
    value4: '4',
    value5: '5',
    value6: '6',
    value7: '7',

    valueA1: 'A1',
    valueA2: 'A2',
    valueB1: 'B1',
    valueB2: 'B2',
    valueB3: 'B3',
    valueB4: 'B4',
    valueB5: 'B5',

    noSelection: 'Não há seleção disponível no momento.',
    tryAgainLater: 'Volte mais tarde.',
    yourRanking: 'Sua colocação:',
    yourScore: 'Sua pontuação é de',
    delete: 'Deletar',
    
    // ERRORS MESSAGES
    USER_NOT_FOUND: {code: 'USER_NOT_FOUND', message: 'Usuário não encontrado.'},
    INVALID_PASSWORD: {code: 'INVALID_PASSWORD', message: 'Senha incorreta.'},
    ERROR_SERVER: 'Houve um erro na conexão com o servidor, tente novamente mais tarde.',
    REQUIRED_FIELD: 'Esse campo é obrigatório',
    FILE_ONLY_PDF: 'Tipo incorreto, somente PDF',
    FILE_SIZE: 'Tamanho máximo de 15 MB excedido',
    EMAIL_INCORRECT: 'Isso não parece um email',
    CHAR_INVALID: 'Caracteres inválidos',
    PASSWORD_SHORT: 'Mínimo de 6 caracteres',
    PASSWORD_DIFF: 'As senhas não são iguais',    
    URL_INVALID: 'URL inválida',
    NOTE_RANGE: 'Nota entre 0 e 10',
}